#!/usr/bin/env bash

# Install oh-my-zsh
if [ -d "$HOME/.oh-my-zsh" ]; then 
  echo "Oh My Zsh is installed. Skipping."
else
  echo "Installing Oh My Zsh..."
  sudo curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
fi

# Install powerlevel10k
if [ -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k" ]; then
  echo "Powerlevel10k is installed. Skipping"
else
  echo "Installing Powerlevel10k..."
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
fi

# Install homebrew
if [ -f /opt/homebrew/bin/brew ]; then
  echo "Homebrew is installed. Skipping."
else
  echo "Installing Homebrew..."
  sudo curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
  eval $(/opt/homebrew/bin/brew shellenv)
fi

# Install neovim
which nvim &> /dev/null
if [ $? -eq 0 ]; then
  echo "Neovim is installed. Skipping."
else
  echo "Installing Neovim..."
  brew install neovim
fi

