#!/usr/bin/env bash

# Install oh-my-zsh
if [ -d "$HOME/.oh-my-zsh" ]; then 
  echo "Oh My Zsh is installed. Skipping."
else
  echo "Installing Oh My Zsh..."
  sudo curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
fi

if [ -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting" ]; then
  echo "zsh-syntax-highlighting is installed. Skipping"
else
  echo "Installing zsh-syntax-highlighting plugin..."
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
fi

if [ -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions" ]; then
  echo "zsh-autosuggestions installed. Skipping"
else
  echo "Installing zsh-autosuggestions plugin..."
  git clone https://github.com/zsh-users/zsh-autosuggestions.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
fi


# Install powerlevel10k
POWERLEVEL_PROMPT=0
if [ -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k" ]; then
  echo "Powerlevel10k is installed. Skipping"
else
  POWERLEVEL_PROMPT=1
  echo "Installing Powerlevel10k..."
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
fi

# Install homebrew
if [ -f /opt/homebrew/bin/brew ]; then
  echo "Homebrew is installed. Skipping."
else
  echo "Installing Homebrew..."
  sudo curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
  eval $(/opt/homebrew/bin/brew shellenv)
fi

# Install neovim
which nvim &> /dev/null
if [ $? -eq 0 ]; then
  echo "Neovim is installed. Skipping."
else
  echo "Installing Neovim..."
  brew install neovim
fi

# Install nvm
if [ -d "$NVM_DIR" ]; then
  echo "nvm is installed. Skipping."
else
  echo "Installing nvm..."
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
fi

which npm &> /dev/null
if [ $? -eq 0 ]; then
  echo "Node already installed. Skipping."
else
  echo "Installing latest version of node..."
  zsh
  nvm install node 16.14.0
  nvm use 16.14.0
fi


# Symlink config files
ln -sf "$(pwd)/.zshrc" "$HOME/.zshrc"
mkdir -p "$HOME/.config/nvim/vim-plug"
ln -sf "$(pwd)/plugins.vim" "$HOME/.config/nvim/vim-plug/plugins.vim"
ln -sf "$(pwd)/init.vim" "$HOME/.config/nvim/init.vim"

# Next steps
if [ $POWERLEVEL_PROMPT -eq 1 ]; then
  echo "To set up Powerlevel10k, use the following command:\e  source ~/.zshrc"
fi
